# Generated by Django 3.2 on 2021-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=2)),
                ('governorate', models.CharField(max_length=300)),
                ('region_city', models.CharField(max_length=300)),
                ('tax_number_id', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=300)),
                ('building_number', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='invoice_line',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('internal_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('taxes', models.CharField(max_length=2)),
                ('rates', models.IntegerField()),
                ('discount', models.FloatField()),
                ('sub_taxes', models.CharField(max_length=4)),
                ('value_difference', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='invoice_result',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('uu_id', models.CharField(max_length=30)),
                ('submission_uu_id', models.CharField(max_length=30)),
                ('state', models.IntegerField()),
                ('errors', models.CharField(max_length=1000)),
            ],
        ),
    ]
